### ISSUE TITLE
java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by ghost** [HypariaMC/EssentialsX#2]
I just tried the latest version of EssentialsX but I encountered this error.
https://gist.github.com/Heliosard/6424ffa906a32c79c17a22e18c746d68

**Comment by Phoenix616** [comment]
What version of the JDK did you use to build this? It looks like there are issues similar to this when using JDK9 to build a JDK8/previous project. Using JDK8 would be the best.

Also I would suggest using the 2.x-hyparia branch instead of the 2.x-per-player-locale to have a different version number and project ID to differentiate the two different them and properly depend on it from other plugins that expect the per-player-locale API.

**Comment by ghost** [comment]
We update the machines under java 11, so I passed the jdk in this version.

**Comment by Phoenix616** [comment]
Well according to the error log you are running the server with Java 8. Maybe it would work when running with Java 11? Not sure about that though, a lot of Minecraft related software seems to not be ready for Java 11 or made with it in mind so there might be unexpected errors like that when using it. E.g. EssentialsX still targets Java 7, could also be possible that this could be worked around by setting the target to Java 11 but I personally think that Java 8 is currently the most stable option for a Minecraft server. (Especially as it is supported until at least 2023 by AdoptOpenJdk, longer than 11 support is currently foreseen to be supported)

Otherwise I would highly recommend using the JDK version that corresponds to the version of the JRE that you are using when running the server for building any plugins/software.

**Comment by ghost** [comment]
We'll listen to your advice and stay in 1.8.
Indeed, by keeping the SDK of Java 1.8 I have no problem with it during compilation.
